# ============================================================
#  Configuracion Mosquitto - Proyecto DataGuard
# ============================================================

# Escuchar en todas las interfaces, puerto 1883 (red local).
# Esto permite que el ESP8266 (otra IP) se conecte al broker.
listener 1883

# Permitir conexiones sin usuario/clave (red local de laboratorio).
# Para produccion: poner 'false' y configurar password_file.
allow_anonymous true

# Persistencia de datos (mensajes retenidos, etc.)
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
